[package]
name = "talib-js"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindgen = "0.66.1"
cc = "1.0.79"
wasm-bindgen = "0.2.87"
